import { FormEvent, useCallback, useEffect, useState } from "react";
import { Building2, Plus, Users } from "lucide-react";
import { atualizarConta, atualizarParceiro, criarConta, criarParceiro, obterConfiguracoesFinanceiras, type Conta, type ConfiguracoesFinanceiras as Config, type Parceiro } from "./novo-api";
import { brl, Button, type ColunaTabela, dataBR, ErrorBox, hoje, PageHeader, PaginaFinanceira, PaginaSemDados, Panel, Pill, TabelaFinanceira } from "./financeiro-ui";
import { newEntityId } from "@fazendinha/shared";

/* Colunas dos dois cadastros. O alinhamento vale para cabeçalho e conteúdo de
 * uma vez só; `alternar` recebe o item porque o toggle depende da linha. */
const colunasContas = (alternar: (conta: Conta) => void): ColunaTabela<Conta>[] => [
  { chave: "conta", titulo: "Conta", larguraMinima: 230, principal: true, celula: (c) => <><strong className="break-words">{c.nome}</strong><div className="mt-1 break-words text-xs text-ink-3">{c.instituicao || c.identificacao || "Sem identificação adicional"}</div></> },
  { chave: "tipo", titulo: "Tipo", larguraMinima: 110, celula: (c) => <span className="whitespace-nowrap">{c.tipo}</span> },
  { chave: "abertura", titulo: "Abertura", alinhamento: "direita", larguraMinima: 130, celula: (c) => <><span className="whitespace-nowrap">{brl(c.saldoAbertura)}</span><div className="whitespace-nowrap text-xs text-ink-3">{dataBR(c.dataSaldoAbertura)}</div></> },
  { chave: "saldo", titulo: "Saldo atual", alinhamento: "direita", larguraMinima: 130, celula: (c) => <strong className="whitespace-nowrap font-semibold">{brl(c.saldoAtual)}</strong> },
  { chave: "situacao", titulo: "Situação", alinhamento: "direita", larguraMinima: 170, celula: (c) => <div className="flex flex-wrap items-center justify-end gap-3"><Pill tone={c.ativo ? "green" : "neutral"}>{c.ativo ? "Ativa" : "Inativa"}</Pill><button onClick={() => alternar(c)} className="text-xs font-semibold text-green-800">{c.ativo ? "Desativar" : "Reativar"}</button></div> },
];

const colunasParceiros = (alternar: (parceiro: Parceiro) => void): ColunaTabela<Parceiro>[] => [
  { chave: "nome", titulo: "Nome", larguraMinima: 200, principal: true, celula: (p) => <strong className="break-words font-semibold">{p.nome}</strong> },
  { chave: "documento", titulo: "Documento", larguraMinima: 125, celula: (p) => <span className="whitespace-nowrap">{p.documento || "—"}</span> },
  { chave: "papel", titulo: "Papel", larguraMinima: 125, celula: (p) => <span className="break-words">{p.tipo.replaceAll("_", " ")}</span> },
  { chave: "contato", titulo: "Contato", larguraMinima: 140, celula: (p) => <span className="break-words text-ink-3">{p.telefone || p.email || "—"}</span> },
  { chave: "situacao", titulo: "Situação", alinhamento: "direita", larguraMinima: 170, celula: (p) => <div className="flex flex-wrap items-center justify-end gap-3"><Pill tone={p.ativo ? "green" : "neutral"}>{p.ativo ? "Ativo" : "Inativo"}</Pill><button onClick={() => alternar(p)} className="text-xs font-semibold text-green-800">{p.ativo ? "Desativar" : "Reativar"}</button></div> },
];

export function ConfiguracoesFinanceiras() {
  const [config, setConfig] = useState<Config | null>(null); const [erro, setErro] = useState<string | null>(null); const [aba, setAba] = useState<"contas" | "parceiros">("contas"); const [criando, setCriando] = useState(false);
  const [nome, setNome] = useState(""); const [tipo, setTipo] = useState("BANCO"); const [saldo, setSaldo] = useState("0"); const [documento, setDocumento] = useState("");
  const [criacaoId, setCriacaoId] = useState(newEntityId);
  const carregar = useCallback(() => obterConfiguracoesFinanceiras().then(setConfig).catch((e) => setErro(e.message)), []); useEffect(() => { carregar(); }, [carregar]);
  if (!config) return <PaginaSemDados titulo="Configurações financeiras" descricao="Cadastros que sustentam as operações. Desativar preserva todo o histórico e permite reativação." label="Carregando configurações financeiras" erro={erro} />;
  const adicionar = async (e: FormEvent) => { e.preventDefault(); try { if (aba === "contas") await criarConta({ id: criacaoId, nome, tipo, saldoAbertura: Number(saldo), dataSaldoAbertura: hoje(), incluirNoSaldoGeral: true }); else await criarParceiro({ id: criacaoId, nome, documento: documento || undefined, tipo }); setNome(""); setDocumento(""); setSaldo("0"); setCriacaoId(newEntityId()); setCriando(false); await carregar(); } catch (e) { setErro(e instanceof Error ? e.message : String(e)); } };

  return <PaginaFinanceira><PageHeader titulo="Configurações financeiras" descricao="Cadastros que sustentam as operações. Desativar preserva todo o histórico e permite reativação." acao={<Button onClick={() => setCriando(true)}><Plus size={16} /> {aba === "contas" ? "Nova conta" : "Novo parceiro"}</Button>} /><ErrorBox erro={erro} />
    <div className="mt-6 flex gap-2 overflow-x-auto border-b border-border">{([['contas', 'Contas financeiras', Building2], ['parceiros', 'Clientes e fornecedores', Users]] as const).map(([k, label, Icon]) => <button key={k} onClick={() => { setAba(k); setTipo(k === "contas" ? "BANCO" : "FORNECEDOR"); setCriacaoId(newEntityId()); setCriando(false); }} className={`flex shrink-0 items-center gap-2 whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${aba === k ? "border-mast text-ink" : "border-transparent text-ink-3"}`}><Icon size={16} className="shrink-0" />{label}</button>)}</div>
    {criando && <Panel className="mt-5"><form onSubmit={adicionar} className="flex flex-wrap items-end gap-4 p-5"><label className="w-full min-w-0 flex-[1_1_240px] text-sm font-medium sm:w-auto">Nome<input required value={nome} onChange={(e) => setNome(e.target.value)} className="mt-1.5 w-full rounded-lg border border-border p-2.5 font-normal" /></label>{aba === "contas" ? <><label className="w-full min-w-0 flex-[1_1_160px] text-sm font-medium sm:w-auto">Tipo<select value={tipo} onChange={(e) => setTipo(e.target.value)} className="mt-1.5 block w-full rounded-lg border border-border bg-white p-2.5 font-normal"><option value="BANCO">Banco</option><option value="CAIXA">Caixa</option><option value="APLICACAO">Aplicação</option><option value="DINHEIRO">Dinheiro</option></select></label><label className="w-full min-w-0 flex-[1_1_160px] text-sm font-medium sm:w-auto">Saldo de abertura<input type="number" step="0.01" value={saldo} onChange={(e) => setSaldo(e.target.value)} className="mt-1.5 block w-full rounded-lg border border-border p-2.5 font-normal" /></label></> : <><label className="w-full min-w-0 flex-[1_1_160px] text-sm font-medium sm:w-auto">Papel<select value={tipo} onChange={(e) => setTipo(e.target.value)} className="mt-1.5 block w-full rounded-lg border border-border bg-white p-2.5 font-normal"><option value="FORNECEDOR">Fornecedor</option><option value="CLIENTE">Cliente</option><option value="AMBOS">Cliente e fornecedor</option><option value="FUNCIONARIO">Funcionário</option><option value="PROPRIETARIO">Proprietário</option><option value="OUTRO">Outro</option></select></label><label className="w-full min-w-0 flex-[1_1_160px] text-sm font-medium sm:w-auto">CPF/CNPJ<input value={documento} onChange={(e) => setDocumento(e.target.value)} className="mt-1.5 block w-full rounded-lg border border-border p-2.5 font-normal" /></label></>}<Button type="submit">Adicionar</Button><Button secondary onClick={() => setCriando(false)}>Cancelar</Button></form></Panel>}
    <Panel className="mt-5 overflow-hidden">{aba === "contas"
      ? <TabelaFinanceira rotulo="Contas financeiras" itens={config.contas} colunas={colunasContas(async (c) => { await atualizarConta(c.id, { ativo: !c.ativo }); carregar(); })} chaveDe={(c) => c.id} classeLinha={(c) => !c.ativo ? "opacity-55" : ""} />
      : <TabelaFinanceira rotulo="Clientes e fornecedores" itens={config.parceiros} colunas={colunasParceiros(async (p) => { await atualizarParceiro(p.id, { ativo: !p.ativo }); carregar(); })} chaveDe={(p) => p.id} classeLinha={(p) => !p.ativo ? "opacity-55" : ""} />}</Panel>
  </PaginaFinanceira>;
}
