import { FormEvent, useCallback, useEffect, useState } from "react";
import { Building2, Plus, Users } from "lucide-react";
import { Loader } from "../components/Loading";
import { atualizarConta, atualizarParceiro, criarConta, criarParceiro, obterConfiguracoesFinanceiras, type ConfiguracoesFinanceiras as Config } from "./novo-api";
import { brl, Button, dataBR, ErrorBox, hoje, PageHeader, Panel, Pill } from "./financeiro-ui";

export function ConfiguracoesFinanceiras() {
  const [config, setConfig] = useState<Config | null>(null); const [erro, setErro] = useState<string | null>(null); const [aba, setAba] = useState<"contas" | "parceiros">("contas"); const [criando, setCriando] = useState(false);
  const [nome, setNome] = useState(""); const [tipo, setTipo] = useState("BANCO"); const [saldo, setSaldo] = useState("0"); const [documento, setDocumento] = useState("");
  const carregar = useCallback(() => obterConfiguracoesFinanceiras().then(setConfig).catch((e) => setErro(e.message)), []); useEffect(() => { carregar(); }, [carregar]);
  if (!config) return <Loader label="Carregando configurações financeiras" />;
  const adicionar = async (e: FormEvent) => { e.preventDefault(); try { if (aba === "contas") await criarConta({ nome, tipo, saldoAbertura: Number(saldo), dataSaldoAbertura: hoje(), incluirNoSaldoGeral: true }); else await criarParceiro({ nome, documento: documento || undefined, tipo }); setNome(""); setDocumento(""); setSaldo("0"); setCriando(false); await carregar(); } catch (e) { setErro(e instanceof Error ? e.message : String(e)); } };

  return <div className="shell-wide pb-10"><PageHeader titulo="Configurações financeiras" descricao="Cadastros que sustentam as operações. Desativar preserva todo o histórico e permite reativação." acao={<Button onClick={() => setCriando(true)}><Plus size={16} /> {aba === "contas" ? "Nova conta" : "Novo parceiro"}</Button>} /><ErrorBox erro={erro} />
    <div className="mt-6 flex gap-2 border-b border-border">{([['contas', 'Contas financeiras', Building2], ['parceiros', 'Clientes e fornecedores', Users]] as const).map(([k, label, Icon]) => <button key={k} onClick={() => { setAba(k); setTipo(k === "contas" ? "BANCO" : "FORNECEDOR"); setCriando(false); }} className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-semibold ${aba === k ? "border-mast text-ink" : "border-transparent text-ink-3"}`}><Icon size={16} />{label}</button>)}</div>
    {criando && <Panel className="mt-5"><form onSubmit={adicionar} className="flex flex-wrap items-end gap-4 p-5"><label className="min-w-60 flex-1 text-sm font-medium">Nome<input required value={nome} onChange={(e) => setNome(e.target.value)} className="mt-1.5 w-full rounded-lg border border-border p-2.5 font-normal" /></label>{aba === "contas" ? <><label className="text-sm font-medium">Tipo<select value={tipo} onChange={(e) => setTipo(e.target.value)} className="mt-1.5 block rounded-lg border border-border bg-white p-2.5 font-normal"><option value="BANCO">Banco</option><option value="CAIXA">Caixa</option><option value="APLICACAO">Aplicação</option><option value="DINHEIRO">Dinheiro</option></select></label><label className="text-sm font-medium">Saldo de abertura<input type="number" step="0.01" value={saldo} onChange={(e) => setSaldo(e.target.value)} className="mt-1.5 block rounded-lg border border-border p-2.5 font-normal" /></label></> : <><label className="text-sm font-medium">Papel<select value={tipo} onChange={(e) => setTipo(e.target.value)} className="mt-1.5 block rounded-lg border border-border bg-white p-2.5 font-normal"><option value="FORNECEDOR">Fornecedor</option><option value="CLIENTE">Cliente</option><option value="AMBOS">Cliente e fornecedor</option><option value="FUNCIONARIO">Funcionário</option><option value="PROPRIETARIO">Proprietário</option><option value="OUTRO">Outro</option></select></label><label className="text-sm font-medium">CPF/CNPJ<input value={documento} onChange={(e) => setDocumento(e.target.value)} className="mt-1.5 block rounded-lg border border-border p-2.5 font-normal" /></label></>}<Button type="submit">Adicionar</Button><Button secondary onClick={() => setCriando(false)}>Cancelar</Button></form></Panel>}
    <Panel className="mt-5 overflow-hidden">{aba === "contas" ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f4f2e9] text-[11px] uppercase tracking-wider text-ink-3"><tr><th className="p-4">Conta</th><th className="p-4">Tipo</th><th className="p-4">Abertura</th><th className="p-4 text-right">Saldo atual</th><th className="p-4 text-right">Situação</th></tr></thead><tbody className="divide-y divide-border">{config.contas.map((c) => <tr key={c.id} className={!c.ativo ? "opacity-55" : ""}><td className="p-4"><strong>{c.nome}</strong><div className="mt-1 text-xs text-ink-3">{c.instituicao || c.identificacao || "Sem identificação adicional"}</div></td><td className="p-4">{c.tipo}</td><td className="p-4">{brl(c.saldoAbertura)}<div className="text-xs text-ink-3">{dataBR(c.dataSaldoAbertura)}</div></td><td className="p-4 text-right font-semibold">{brl(c.saldoAtual)}</td><td className="p-4 text-right"><Pill tone={c.ativo ? "green" : "neutral"}>{c.ativo ? "Ativa" : "Inativa"}</Pill><button onClick={async () => { await atualizarConta(c.id, { ativo: !c.ativo }); carregar(); }} className="ml-3 text-xs font-semibold text-green-800">{c.ativo ? "Desativar" : "Reativar"}</button></td></tr>)}</tbody></table></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f4f2e9] text-[11px] uppercase tracking-wider text-ink-3"><tr><th className="p-4">Nome</th><th className="p-4">Documento</th><th className="p-4">Papel</th><th className="p-4">Contato</th><th className="p-4 text-right">Situação</th></tr></thead><tbody className="divide-y divide-border">{config.parceiros.map((p) => <tr key={p.id} className={!p.ativo ? "opacity-55" : ""}><td className="p-4 font-semibold">{p.nome}</td><td className="p-4">{p.documento || "—"}</td><td className="p-4">{p.tipo.replaceAll("_", " ")}</td><td className="p-4 text-ink-3">{p.telefone || p.email || "—"}</td><td className="p-4 text-right"><Pill tone={p.ativo ? "green" : "neutral"}>{p.ativo ? "Ativo" : "Inativo"}</Pill><button onClick={async () => { await atualizarParceiro(p.id, { ativo: !p.ativo }); carregar(); }} className="ml-3 text-xs font-semibold text-green-800">{p.ativo ? "Desativar" : "Reativar"}</button></td></tr>)}</tbody></table></div>}</Panel>
  </div>;
}
