import { useCallback, useEffect, useMemo, useState } from "react";
import { ChevronRight, Download, Plus, Search, SlidersHorizontal, X } from "lucide-react";
import { Loader } from "../components/Loading";
import { estornarOperacao, listarOperacoes, obterConfiguracoesFinanceiras, type ConfiguracoesFinanceiras, type Operacao } from "./novo-api";
import { FormOperacao } from "./FormOperacao";
import { brl, Button, dataBR, Empty, ErrorBox, PageHeader, Panel, Pill, StatusPill, TIPO_OPERACAO } from "./financeiro-ui";

function Efeitos({ operacao }: { operacao: Operacao }) {
  const estoque = operacao.movimentosEstoque?.length > 0; const transacoes = operacao.transacoes ?? []; const compromissos = operacao.compromissos ?? [];
  return <div className="flex flex-wrap gap-1.5">{estoque && <Pill tone="brown">estoque</Pill>}{transacoes.length > 0 && <Pill tone="green">{transacoes.some((t) => t.tipo === "RECEBIMENTO") ? "recebimento" : transacoes.some((t) => t.tipo === "TRANSFERENCIA") ? "transferência" : "pagamento"}</Pill>}{compromissos.length > 0 && <Pill tone="amber">{compromissos[0]?.tipo === "RECEBER" ? "a receber" : "a pagar"}</Pill>}{!estoque && !transacoes.length && !compromissos.length && <Pill>sem efeitos</Pill>}</div>;
}

export function OperacoesFinanceiras() {
  const [itens, setItens] = useState<Operacao[]>([]); const [config, setConfig] = useState<ConfiguracoesFinanceiras | null>(null); const [form, setForm] = useState(false); const [loading, setLoading] = useState(true); const [erro, setErro] = useState<string | null>(null);
  const [busca, setBusca] = useState(""); const [status, setStatus] = useState("TODOS"); const [tipo, setTipo] = useState("TODOS"); const [selecionada, setSelecionada] = useState<Operacao | null>(null); const [motivo, setMotivo] = useState(""); const [confirmandoEstorno, setConfirmandoEstorno] = useState(false);
  const carregar = useCallback(async () => { setLoading(true); setErro(null); try { const [ops, cfg] = await Promise.all([listarOperacoes(), obterConfiguracoesFinanceiras()]); setItens(ops); setConfig(cfg); setSelecionada((atual) => atual ? ops.find((o) => o.id === atual.id) ?? null : null); } catch (e) { setErro(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void carregar(); }, [carregar]);
  const filtradas = useMemo(() => itens.filter((o) => (status === "TODOS" || o.status === status) && (tipo === "TODOS" || o.tipo === tipo) && `${o.descricao} ${o.parceiro?.nome} ${o.id}`.toLowerCase().includes(busca.toLowerCase())), [itens, busca, status, tipo]);
  if (loading && !config) return <Loader label="Carregando operações" />;

  return <div className="shell-wide pb-10">
    <PageHeader titulo="Operações" descricao="Compras, vendas e serviços com todos os efeitos financeiros e físicos reunidos no mesmo registro." acao={<Button onClick={() => { setSelecionada(null); setForm(true); }}><Plus size={16} /> Nova operação</Button>} />
    {form && config && <FormOperacao config={config} onCancelar={() => setForm(false)} onSalvo={async (aviso) => { setForm(false); await carregar(); if (aviso) setErro(aviso); }} />}
    <ErrorBox erro={erro} />
    <Panel className="mt-6 overflow-hidden">
      <div className="flex flex-wrap items-center gap-3 border-b border-border p-4"><label className="relative min-w-64 flex-1"><Search size={16} className="absolute left-3 top-3 text-ink-3" /><input aria-label="Buscar operações" value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar por operação, parceiro ou número" className="w-full rounded-lg border border-border py-2.5 pl-9 pr-3 text-sm" /></label><label className="flex items-center gap-2 text-sm text-ink-3"><SlidersHorizontal size={15} /><select aria-label="Filtrar por tipo" value={tipo} onChange={(e) => setTipo(e.target.value)} className="rounded-lg border border-border bg-white p-2.5 text-ink"><option value="TODOS">Todos os tipos</option>{Object.entries(TIPO_OPERACAO).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><select aria-label="Filtrar por status" value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border border-border bg-white p-2.5 text-sm"><option value="TODOS">Todos os status</option><option value="CONFIRMADA">Confirmadas</option><option value="CANCELADA">Canceladas</option></select></div>
      {filtradas.length ? <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-[#f4f2e9] text-[11px] uppercase tracking-[.08em] text-ink-3"><tr><th className="p-4">Data</th><th className="p-4">Operação</th><th className="p-4">Parceiro</th><th className="p-4">Efeitos</th><th className="p-4">Status</th><th className="p-4 text-right">Valor</th><th className="w-10" /></tr></thead><tbody className="divide-y divide-border">{filtradas.map((o) => <tr key={o.id} onClick={() => { setForm(false); setSelecionada(o); setConfirmandoEstorno(false); setMotivo(""); }} className={`cursor-pointer hover:bg-[#faf9f4] ${o.status === "CANCELADA" ? "opacity-60" : ""}`}><td className="p-4 text-ink-3">{dataBR(o.data)}</td><td className="p-4"><strong>{o.descricao || TIPO_OPERACAO[o.tipo]}</strong><div className="mt-1 text-xs text-ink-3">OP-{String(o.id).padStart(4, "0")} · {TIPO_OPERACAO[o.tipo] ?? o.tipo}</div></td><td className="p-4">{o.parceiro?.nome ?? "—"}</td><td className="p-4"><Efeitos operacao={o} /></td><td className="p-4"><StatusPill status={o.status} /></td><td className="p-4 text-right font-semibold">{brl(o.valorTotal)}</td><td className="pr-4"><ChevronRight size={16} className="text-ink-3" /></td></tr>)}</tbody></table></div> : <Empty>Nenhuma operação encontrada com esses filtros.</Empty>}
    </Panel>

    {selecionada && <Panel className="mt-6 overflow-hidden">
      <div className="flex items-start justify-between border-b border-border bg-[#f4f2e9] p-5"><div><div className="flex flex-wrap items-center gap-2"><span className="eyebrow">OP-{String(selecionada.id).padStart(4, "0")}</span><StatusPill status={selecionada.status} /></div><h2 className="mt-2 font-serif text-2xl">{selecionada.descricao || TIPO_OPERACAO[selecionada.tipo]}</h2><p className="mt-1 text-sm text-ink-3">{TIPO_OPERACAO[selecionada.tipo]} · {dataBR(selecionada.data)} · {selecionada.parceiro?.nome ?? "Sem parceiro"}</p></div><button onClick={() => setSelecionada(null)} className="rounded-lg p-2 text-ink-3 hover:bg-white"><X size={18} /></button></div>
      <div className="grid lg:grid-cols-3">
        <div className="border-b border-border p-5 lg:border-b-0 lg:border-r"><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-3">Itens</h3><div className="mt-4 space-y-3">{selecionada.itens?.length ? selecionada.itens.map((i) => <div key={i.id} className="flex justify-between gap-3 text-sm"><div><strong>{i.descricao}</strong><div className="text-xs text-ink-3">{Number(i.quantidade)} {i.unidade} × {brl(i.valorUnitario)}</div></div><strong>{brl(i.valorTotal)}</strong></div>) : <p className="text-sm text-ink-3">Operação sem itens físicos.</p>}</div></div>
        <div className="border-b border-border p-5 lg:border-b-0 lg:border-r"><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-3">Efeitos gerados</h3><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span>Transações financeiras</span><strong>{selecionada.transacoes?.length ?? 0}</strong></div><div className="flex justify-between"><span>Compromissos futuros</span><strong>{selecionada.compromissos?.length ?? 0}</strong></div><div className="flex justify-between"><span>Movimentos de estoque</span><strong>{selecionada.movimentosEstoque?.length ?? 0}</strong></div></div></div>
        <div className="p-5"><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-3">Valor da operação</h3><div className="mt-3 font-serif text-3xl">{brl(selecionada.valorTotal)}</div>{selecionada.status !== "CANCELADA" && <div className="mt-5">{confirmandoEstorno ? <div className="space-y-3"><p className="text-xs leading-5 text-red-800">O sistema criará movimentos inversos e preservará o histórico. Informe o motivo.</p><textarea aria-label="Motivo do estorno" value={motivo} onChange={(e) => setMotivo(e.target.value)} className="min-h-20 w-full rounded-lg border border-red-200 p-2.5 text-sm" placeholder="Motivo obrigatório" /><div className="flex flex-wrap gap-2"><Button danger disabled={motivo.trim().length < 5} onClick={async () => { try { await estornarOperacao(selecionada.id, motivo.trim()); await carregar(); setConfirmandoEstorno(false); } catch (e) { setErro(e instanceof Error ? e.message : String(e)); } }}>Confirmar estorno</Button><Button secondary onClick={() => setConfirmandoEstorno(false)}>Cancelar</Button></div></div> : <button onClick={() => setConfirmandoEstorno(true)} className="text-sm font-semibold text-red-800">Estornar operação</button>}</div>}</div>
      </div>
      <div className="border-t border-border p-5"><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-3">Documentos</h3><p className="mt-1 text-xs text-ink-3">Arquivos vinculados à origem da operação.</p></div><strong className="text-sm">{selecionada.documentos?.length ?? 0}</strong></div>{selecionada.documentos?.length ? <div className="mt-4 grid gap-2 md:grid-cols-2">{selecionada.documentos.map((documento) => <a key={documento.id} href={`/api/financeiro/documentos/${documento.id}/download`} className="flex items-center justify-between rounded-lg border border-border p-3 text-sm hover:bg-[#faf9f4]"><span><strong>{documento.nome}</strong><span className="mt-0.5 block text-xs text-ink-3">{documento.tipo.replaceAll("_", " ")}{documento.numero ? ` · ${documento.numero}` : ""}</span></span><Download size={16} className="text-ink-3" /></a>)}</div> : <p className="mt-4 text-sm text-ink-3">Nenhum documento anexado.</p>}</div>
    </Panel>}
  </div>;
}
