import { AnaliseCategorias } from "./AnaliseCategorias";
import { useEffect, useState } from "react";
import { Download, FilePlus2, RotateCcw, Trash2 } from "lucide-react";
import { baixarRelatorioFinanceiro, descartarRascunhoRelatorioFinanceiro, gerarRelatorioFinanceiro, listarRelatoriosFinanceiros, obterConfiguracoesFinanceiras, obterRascunhoRelatorioFinanceiro, salvarRascunhoRelatorioFinanceiro, type ConfiguracaoRelatorioFinanceiro, type RelatorioFinanceiro } from "./novo-api";
import { Button, Empty, ErrorBox, PageHeader, PaginaCarregando, PaginaFinanceira, Panel, StatusPill, TIPO_OPERACAO } from "./financeiro-ui";

const tipos = Object.entries(TIPO_OPERACAO).filter(([tipo]) => tipo !== "TRANSFERENCIA_FINANCEIRA");
const padrao = (): ConfiguracaoRelatorioFinanceiro => ({ nome: "Relatório financeiro", dataInicio: `${new Date().getFullYear()}-01-01`, dataFim: new Date().toISOString().slice(0, 10), tipos: [], status: ["CONFIRMADA"], centroCustoIds: [] });
const dataHora = (valor: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(valor));

export function RelatoriosFinanceiros() {
  const [relatorios, setRelatorios] = useState<RelatorioFinanceiro[]>([]);
  const [config, setConfig] = useState(padrao); const [versao, setVersao] = useState<number | undefined>();
  const [centros, setCentros] = useState<{ id: number; nome: string }[]>([]); const [aberto, setAberto] = useState(false);
  const [carregando, setCarregando] = useState(true); const [gerando, setGerando] = useState(false); const [erro, setErro] = useState<string | null>(null);
  const recarregar = () => listarRelatoriosFinanceiros().then(setRelatorios);
  useEffect(() => { Promise.all([recarregar(), obterConfiguracoesFinanceiras(), obterRascunhoRelatorioFinanceiro()]).then(([, dados, rascunho]) => { setCentros(dados.centrosCusto); if (rascunho) { setConfig(rascunho.configuracao); setVersao(rascunho.versao); setAberto(true); } }).catch((e) => setErro(e.message)).finally(() => setCarregando(false)); }, []);
  useEffect(() => { if (!aberto) return; const timer = window.setTimeout(() => { salvarRascunhoRelatorioFinanceiro(config, versao).then((r) => setVersao(r.versao)).catch((e) => setErro(e.message)); }, 700); return () => window.clearTimeout(timer); }, [aberto, config]);
  const marcar = (campo: "tipos" | "status" | "centroCustoIds", valor: string | number) => setConfig((atual) => ({ ...atual, [campo]: atual[campo].includes(valor as never) ? atual[campo].filter((item) => item !== valor) : [...atual[campo], valor] }));
  const novo = () => { setConfig(padrao()); setVersao(undefined); setAberto(true); };
  const limpar = async () => { await descartarRascunhoRelatorioFinanceiro(); setConfig(padrao()); setVersao(undefined); };
  const baixar = async (r: RelatorioFinanceiro) => { try { const blob = await baixarRelatorioFinanceiro(r.id); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${r.nome}.pdf`; a.click(); URL.revokeObjectURL(url); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível baixar o PDF."); } };
  const gerar = async () => { setErro(null); setGerando(true); try { const criado = await gerarRelatorioFinanceiro(config); await recarregar(); setAberto(false); const r = (await listarRelatoriosFinanceiros()).find((item) => item.id === criado.id); if (r?.status === "CONCLUIDO") await baixar(r); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível gerar o relatório."); } finally { setGerando(false); } };
  if (carregando) return <PaginaCarregando label="Carregando relatórios" />;
  return <PaginaFinanceira><PageHeader titulo="Relatórios financeiros" descricao="Gere um recorte auditável das operações e acesse os PDFs já emitidos." acao={<Button onClick={novo}><FilePlus2 size={16} /> Novo relatório</Button>} /><ErrorBox erro={erro} />
    {aberto && <Panel className="mt-6"><div className="border-b border-border p-5"><h2 className="font-serif text-xl">Configurar relatório</h2><p className="mt-1 text-sm text-ink-3">O rascunho é salvo automaticamente para sua conta.</p></div><div className="grid gap-5 p-5 lg:grid-cols-2"><label className="text-sm font-medium">Nome<input value={config.nome} onChange={(e) => setConfig({ ...config, nome: e.target.value })} className="mt-1 w-full rounded-lg border border-border p-2" /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Data inicial<input type="date" value={config.dataInicio} onChange={(e) => setConfig({ ...config, dataInicio: e.target.value })} className="mt-1 w-full rounded-lg border border-border p-2" /></label><label className="text-sm font-medium">Data final<input type="date" value={config.dataFim} onChange={(e) => setConfig({ ...config, dataFim: e.target.value })} className="mt-1 w-full rounded-lg border border-border p-2" /></label></div>
      <Filtros titulo="Tipos de operação" itens={tipos.map(([id, nome]) => [id, nome] as const)} selecionados={config.tipos} aoAlternar={(id) => marcar("tipos", id)} /><Filtros titulo="Centro de custo" itens={centros.map((c) => [c.id, c.nome] as const)} selecionados={config.centroCustoIds} aoAlternar={(id) => marcar("centroCustoIds", id)} /><Filtros titulo="Situação" itens={[["CONFIRMADA", "Confirmada"], ["RASCUNHO", "Rascunho"], ["CANCELADA", "Cancelada"]]} selecionados={config.status} aoAlternar={(id) => marcar("status", id)} /></div><div className="flex flex-wrap justify-end gap-3 border-t border-border p-5"><Button secondary onClick={limpar}><Trash2 size={16} /> Limpar rascunho</Button><Button onClick={gerar} disabled={gerando || !config.nome.trim()}><FilePlus2 size={16} /> {gerando ? "Gerando…" : "Gerar e baixar PDF"}</Button></div></Panel>}
    <Panel className="mt-6"><div className="flex items-center justify-between gap-4 border-b border-border p-5"><div><h2 className="font-serif text-xl">Histórico</h2><p className="mt-1 text-sm text-ink-3">Arquivos ficam vinculados à propriedade e preservam o recorte usado na emissão.</p></div><button onClick={() => recarregar().catch((e) => setErro(e.message))} aria-label="Atualizar histórico" className="rounded-lg p-2 hover:bg-surface-2"><RotateCcw size={17} /></button></div>{relatorios.length === 0 ? <Empty>Nenhum relatório foi gerado ainda.</Empty> : <div className="divide-y divide-border">{relatorios.map((r) => <div key={r.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex flex-wrap items-center gap-2"><strong>{r.nome}</strong><StatusPill status={r.status} /></div><p className="mt-1 text-sm text-ink-3">{dataHora(r.geradoEm)} · {r.autor} · {r.parametros.dataInicio} a {r.parametros.dataFim}</p>{r.erro && <p className="mt-1 text-sm text-red-700">{r.erro}</p>}</div>{r.status === "CONCLUIDO" && <Button secondary onClick={() => baixar(r)}><Download size={16} /> Baixar PDF</Button>}</div>)}</div>}</Panel>
    <AnaliseCategorias />
  </PaginaFinanceira>;
}

function Filtros({ titulo, itens, selecionados, aoAlternar }: { titulo: string; itens: readonly (readonly [string | number, string])[]; selecionados: readonly (string | number)[]; aoAlternar: (id: string | number) => void }) {
  return <fieldset><legend className="text-sm font-medium">{titulo}</legend><div className="mt-2 flex flex-wrap gap-2">{itens.map(([id, nome]) => <label key={String(id)} className="flex cursor-pointer items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm"><input type="checkbox" checked={selecionados.includes(id)} onChange={() => aoAlternar(id)} />{nome}</label>)}</div></fieldset>;
}
