import { useEffect, useState } from "react";
import { DatePicker } from "../../../components/DatePicker";
import { ConfirmacaoCiencia } from "../../../components/ConfirmacaoCiencia";
import { classeInput } from "../../../financeiro/PainelCadastro";
import { hoje } from "../../../financeiro/financeiro-ui";
import { UNIDADES, UNIDADES_ORDENADAS } from "../../../lib/unidades";
import type { ProdutoDTO } from "../../../estoque/api";
import { listarPartidasNutricionais, type PartidaNutricional } from "../nutricao/api";
import type { AplicacaoInput, EstadoPrazo, TipoAplicacao } from "./api";
export type AjusteEtapaAplicacao = Partial<AplicacaoInput> & { motivoDesvio?: string };
export function AjusteIndividualAplicacao({ brinco, ajuste, comum, produtos, tipos, onChange }: { brinco: string; ajuste: AjusteEtapaAplicacao; comum: { propriedadeId: number; data: string; hora: string; produtoId: string; tipoAplicacaoId: string; unidadeDose: string; via: string; responsavel: string; partidaId: string; origemInsumo: AplicacaoInput["origemInsumo"]; estadoCarenciaLeite: EstadoPrazo; estadoCarenciaCarne: EstadoPrazo; carenciaLeiteHoras: number | null; carenciaCarneHoras: number | null }; produtos: ProdutoDTO[]; tipos: TipoAplicacao[]; onChange: (patch: AjusteEtapaAplicacao) => void }) {
  const [partidas, setPartidas] = useState<PartidaNutricional[]>([]);
  const [erro, setErro] = useState<string | null>(null);
  const produtoId = ajuste.produtoId ?? comum.produtoId;
  const produto = produtos.find((p) => p.id === produtoId);
  const data = ajuste.data ?? comum.data;
  const hora = ajuste.aplicadaEm ? new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(ajuste.aplicadaEm)) : comum.hora;
  const partidaId = ajuste.partidaId ?? comum.partidaId;
  const partida = partidas.find((p) => p.id === partidaId);
  useEffect(() => { let vivo = true; setPartidas([]); setErro(null); if (produto?.rastrearPartidas && comum.origemInsumo === "BAIXA_ESTOQUE") listarPartidasNutricionais(produtoId, comum.propriedadeId).then((v) => { if (vivo) setPartidas(v); }).catch((e: unknown) => { if (vivo) setErro(e instanceof Error ? e.message : String(e)); }); return () => { vivo = false; }; }, [produtoId, produto?.rastrearPartidas, comum.propriedadeId, comum.origemInsumo]);
  function mudarData(d: string, h: string) { onChange({ data: d, ...(d && h ? { aplicadaEm: new Date(`${d}T${h}:00-03:00`).toISOString() } : {}), cienciaValidadeDesconhecida: false, documentacaoExcepcional: false, motivoDocumentacaoExcepcional: undefined }); }
  function mudarProduto(id: string) { const p = produtos.find((v) => v.id === id); onChange({ produtoId: id, nomeProdutoAplicado: p?.nome, unidadeDose: p?.unidade, via: p?.perfilSanitario?.viaPadrao ?? "", partidaId: "", itemCompraDiretaId: undefined, cienciaValidadeDesconhecida: false, documentacaoExcepcional: false, motivoDocumentacaoExcepcional: undefined, estadoCarenciaLeite: "NAO_INFORMADO", estadoCarenciaCarne: "NAO_INFORMADO", carenciaLeiteHoras: null, carenciaCarneHoras: null, justificativaCarenciaCarne: "" }); }
  return <details className="grid gap-3 rounded-lg border border-border p-3"><summary>Ajustes individuais de {brinco}</summary>{erro && <p role="alert">{erro}</p>}<div className="grid gap-3 sm:grid-cols-2"><label>Data individual<DatePicker max={hoje()} value={data} onChange={(v) => mudarData(v, hora)} /></label><label>Hora individual<input type="time" className={classeInput} value={hora} onChange={(e) => mudarData(data, e.target.value)} /></label></div>
    {comum.origemInsumo !== "COMPRA_CONSUMO_DIRETO" && <label>Produto individual<select className={classeInput} value={produtoId} onChange={(e) => mudarProduto(e.target.value)}><option value="">Selecione</option>{produtos.filter((p) => p.usoSanitario).map((p) => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label>}
    <label>Unidade individual<select className={classeInput} value={ajuste.unidadeDose ?? comum.unidadeDose} onChange={(e) => onChange({ unidadeDose: e.target.value })}>{UNIDADES_ORDENADAS.filter((u) => !produto || UNIDADES[u].base === UNIDADES[produto.unidade].base).map((u) => <option key={u} value={u}>{UNIDADES[u].rotulo}</option>)}</select></label>
    {comum.origemInsumo === "BAIXA_ESTOQUE" && produto?.rastrearPartidas && <label>Lote individual<select required className={classeInput} value={partidaId} onChange={(e) => onChange({ partidaId: e.target.value, cienciaValidadeDesconhecida: false, documentacaoExcepcional: false, motivoDocumentacaoExcepcional: undefined })}><option value="">Selecione</option>{partidas.map((p) => <option key={p.id} value={p.id}>{p.codigo} · saldo {p.saldo} · validade {p.validade?.slice(0, 10) ?? "não informada"}</option>)}</select></label>}
    {partida?.validade === null && <ConfirmacaoCiencia id={`individual-validade-${brinco}`} checked={ajuste.cienciaValidadeDesconhecida ?? false} onChange={(v) => onChange({ cienciaValidadeDesconhecida: v })}>Confirmo validade não informada de {brinco}</ConfirmacaoCiencia>}
    {partida?.validade && partida.validade.slice(0, 10) < data && <><ConfirmacaoCiencia id={`individual-vencida-${brinco}`} checked={ajuste.documentacaoExcepcional ?? false} onChange={(v) => onChange({ documentacaoExcepcional: v })}>Confirmo que a aplicação de {brinco} já ocorreu com lote vencido</ConfirmacaoCiencia><label>Motivo do fato com lote vencido<textarea className={classeInput} minLength={5} maxLength={500} value={ajuste.motivoDocumentacaoExcepcional ?? ""} onChange={(e) => onChange({ motivoDocumentacaoExcepcional: e.target.value })} /></label></>}
    <label>Tipo individual<select className={classeInput} value={ajuste.tipoAplicacaoId ?? comum.tipoAplicacaoId} onChange={(e) => onChange({ tipoAplicacaoId: e.target.value })}>{tipos.map((t) => <option key={t.id} value={t.id}>{t.nome}</option>)}</select></label><label>Via individual<input className={classeInput} maxLength={80} value={ajuste.via ?? comum.via} onChange={(e) => onChange({ via: e.target.value })} /></label><label>Responsável individual<input className={classeInput} maxLength={160} value={ajuste.responsavel ?? comum.responsavel} onChange={(e) => onChange({ responsavel: e.target.value })} /></label>
    <fieldset className="grid gap-3"><legend>Carência individual</legend>{(["Leite", "Carne"] as const).map((destino) => { const leite = destino === "Leite"; const estado = leite ? ajuste.estadoCarenciaLeite ?? comum.estadoCarenciaLeite : ajuste.estadoCarenciaCarne ?? comum.estadoCarenciaCarne; const prazo = leite ? ajuste.carenciaLeiteHoras ?? comum.carenciaLeiteHoras : ajuste.carenciaCarneHoras ?? comum.carenciaCarneHoras; return <div key={destino}><label>{destino}<select className={classeInput} value={estado} onChange={(e) => onChange(leite ? { estadoCarenciaLeite: e.target.value as EstadoPrazo } : { estadoCarenciaCarne: e.target.value as EstadoPrazo })}><option value="NAO_INFORMADO">Não informado</option><option value="INFORMADO">Prazo informado</option><option value="NAO_APLICAVEL">Não se aplica — confirmado</option></select></label>{estado === "INFORMADO" && <label>Horas de {destino.toLowerCase()}<input type="number" min="0" step="1" className={classeInput} value={prazo ?? ""} onChange={(e) => onChange(leite ? { carenciaLeiteHoras: e.target.value === "" ? null : Number(e.target.value) } : { carenciaCarneHoras: e.target.value === "" ? null : Number(e.target.value) })} /></label>}{!leite && estado === "NAO_APLICAVEL" && <label>Justificativa da carne<textarea maxLength={500} className={classeInput} value={ajuste.justificativaCarenciaCarne ?? ""} onChange={(e) => onChange({ justificativaCarenciaCarne: e.target.value })} /></label>}</div>; })}</fieldset>
    <label>Motivo individual<textarea maxLength={500} className={classeInput} value={ajuste.motivoDesvio ?? ""} placeholder="Usar motivo comum" onChange={(e) => onChange({ motivoDesvio: e.target.value })} /></label>
  </details>;
}
