BEGIN;

ALTER TABLE "GrupoCategoria"
  ADD COLUMN "ativo" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Categoria"
  ADD COLUMN "ativo" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "ordem" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "CentroCusto"
  ADD COLUMN "ativo" BOOLEAN NOT NULL DEFAULT true;

COMMIT;
