/* Inventário reproduzível da Reprodução no IDEAGRI (fonte de verdade da paridade).
 *
 * Rodar contra uma CÓPIA do DADOS777.FDB via scripts/extract-ideagri-repro-inventory.sh.
 * Não extrai dados pessoais nem blobs: somente telas/funções oficiais, nomes de tabelas,
 * colunas técnicas e contagens agregadas das fontes do domínio.
 */
SET HEADING OFF;
SET WIDTH LINHA 4000;

/* Telas oficiais que delimitam a superfície funcional da reprodução. */
SELECT '@TELA@' || CAST(t.CDTELA AS VARCHAR(20))
  || '~|~' || COALESCE(t.CAMINHO, '')
  || '~|~' || COALESCE(t.DESCRICAO, '')
  || '~|~' || COALESCE(t.IDUNICO, '')
  || '~|~' || COALESCE(t.LINK, '') AS "LINHA"
FROM TELA t
WHERE t.CDTELA IN (2, 4, 16, 22, 48, 66, 68, 99, 102, 105, 108, 111, 114, 127, 128, 129)
ORDER BY t.CDTELA;

/* Funções oficiais correspondentes — inclui duplicatas customizadas da fazenda 777. */
SELECT '@FUNCAO@' || CAST(f.CDFUNCAO AS VARCHAR(20))
  || '~|~' || COALESCE(f.CAMINHO, '')
  || '~|~' || COALESCE(f.DESCRICAO, '')
  || '~|~' || COALESCE(f.IDUNICO, '') AS "LINHA"
FROM FUNCAO f
WHERE f.CDFUNCAO IN (1, 25, 27, 28, 30, 31, 32, 81, 83, 92, 96, 113, 115, 147, 148, 150, 157, 162, 164, 167, 168, 169)
ORDER BY f.CDFUNCAO;

/* Contagens-base para reconciliar o histórico da fazenda 777. */
SELECT '@COUNT@REPRODUCAO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM REPRODUCAO;
SELECT '@COUNT@ANIMALINFO_REPRODUCAO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM ANIMALINFO_REPRODUCAO;
SELECT '@COUNT@PROGRAMACAOIATF~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM PROGRAMACAOIATF;
SELECT '@COUNT@PROGRAMACAOIATFASSOCIACAO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM PROGRAMACAOIATFASSOCIACAO;
SELECT '@COUNT@PROTOCOLOIATF~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM PROTOCOLOIATF;
SELECT '@COUNT@PROTOCOLOIATFPRINCIPIOATIVO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM PROTOCOLOIATFPRINCIPIOATIVO;
SELECT '@COUNT@EXAMEANIMAL~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM EXAMEANIMAL;
SELECT '@COUNT@RESULTADOEXAMEGINECOLOGICO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM RESULTADOEXAMEGINECOLOGICO;
SELECT '@COUNT@ANIMALINFO_REPRODUTOR~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM ANIMALINFO_REPRODUTOR;
SELECT '@COUNT@CENTRALSEMEN~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM CENTRALSEMEN;
SELECT '@COUNT@GENCATALOGOINDICADOR~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM GENCATALOGOINDICADOR;
SELECT '@COUNT@GENCATALOGOMARCADOR~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM GENCATALOGOMARCADOR;
SELECT '@COUNT@GENCATALOGOCASEINA~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM GENCATALOGOCASEINA;
SELECT '@COUNT@COLETA~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM COLETA;
SELECT '@COUNT@GRUPOPOOLDOADORA~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM GRUPOPOOLDOADORA;
SELECT '@COUNT@AUXILIOPARTO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM AUXILIOPARTO;
SELECT '@COUNT@EMBRIAOCLASSIFICACAO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM EMBRIAOCLASSIFICACAO;
SELECT '@COUNT@TIPOSEMEN~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM TIPOSEMEN;
SELECT '@COUNT@DADOSCOLETA~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM DADOSCOLETA;
SELECT '@COUNT@DADOSCOLETAITEMINSEMINACAO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM DADOSCOLETAITEMINSEMINACAO;
SELECT '@COUNT@DADOSCOLETAITEMDIAGNOSTICO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM DADOSCOLETAITEMDIAGNOSTICO;
SELECT '@COUNT@DADOSCOLETAITEMPARTO~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM DADOSCOLETAITEMPARTO;
SELECT '@COUNT@DADOSCOLETAITEMSEMEN~|~' || CAST(COUNT(*) AS VARCHAR(20)) AS "LINHA" FROM DADOSCOLETAITEMSEMEN;

/* Colunas técnicas das fontes centrais — evita inventar campos no target. */
SELECT '@COL@' || TRIM(rf.RDB$RELATION_NAME)
  || '~|~' || TRIM(rf.RDB$FIELD_NAME)
  || '~|~' || CAST(rf.RDB$FIELD_POSITION AS VARCHAR(6)) AS "LINHA"
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) IN (
  'REPRODUCAO', 'TIPOREPRODUCAO', 'ANIMALINFO_REPRODUCAO',
  'PROGRAMACAOIATF', 'PROGRAMACAOIATFASSOCIACAO', 'PROTOCOLOIATF',
  'PROTOCOLOIATFPRINCIPIOATIVO', 'EXAMEANIMAL', 'EXAME',
  'RESULTADOEXAMEGINECOLOGICO', 'ANIMALINFO_REPRODUTOR', 'CENTRALSEMEN',
  'GENCATALOGOINDICADOR', 'GENCATALOGOMARCADOR', 'GENCATALOGOCASEINA',
  'GENPROVA', 'GENVALORIND', 'GENPEDIGREE', 'COLETA', 'GRUPOPOOLDOADORA',
  'AUXILIOPARTO', 'TIPOPARTO', 'EMBRIAOCLASSIFICACAO', 'TIPOSEMEN',
  'DADOSCOLETA', 'DADOSCOLETAITEMINSEMINACAO', 'DADOSCOLETAITEMDIAGNOSTICO',
  'DADOSCOLETAITEMPARTO', 'DADOSCOLETAITEMSEMEN'
)
ORDER BY rf.RDB$RELATION_NAME, rf.RDB$FIELD_POSITION;

/* Tipos históricos — prova a distinção IA / cobrição / TE / DG / parto. */
SELECT '@TIPOREPRO@' || CAST(tr.CDTIPOREPRODUCAO AS VARCHAR(10))
  || '~|~' || COALESCE(tr.DESCRICAO, '')
  || '~|~' || CAST(COUNT(r.CDREPRODUCAO) AS VARCHAR(20)) AS "LINHA"
FROM TIPOREPRODUCAO tr
LEFT JOIN REPRODUCAO r ON r.CDTIPOREPRODUCAO = tr.CDTIPOREPRODUCAO
GROUP BY tr.CDTIPOREPRODUCAO, tr.DESCRICAO
ORDER BY tr.CDTIPOREPRODUCAO;

/* Dicionários pequenos necessários para copiar a semântica exata. */
SELECT '@TIPOPARTO@' || CAST(tp.CDTIPOPARTO AS VARCHAR(10))
  || '~|~' || COALESCE(tp.DESCRICAO, '') || '~|~' || COALESCE(tp.SIGLA, '') AS "LINHA"
FROM TIPOPARTO tp ORDER BY tp.CDTIPOPARTO;

SELECT '@AUXILIOPARTO@' || CAST(ap.CDAUXILIOPARTO AS VARCHAR(10))
  || '~|~' || COALESCE(ap.DESCRICAO, '') || '~|~' || COALESCE(ap.SIGLA, '') AS "LINHA"
FROM AUXILIOPARTO ap ORDER BY ap.CDAUXILIOPARTO;

SELECT '@TIPOSEMEN@' || CAST(ts.CDTIPOSEMEN AS VARCHAR(10))
  || '~|~' || COALESCE(ts.NOME, '') AS "LINHA"
FROM TIPOSEMEN ts ORDER BY ts.CDTIPOSEMEN;

SELECT '@EMBRIAOCLASSIFICACAO@' || CAST(ec.CDEMBRIAOCLASSIFICACAO AS VARCHAR(10))
  || '~|~' || COALESCE(ec.DESCRICAO, '') AS "LINHA"
FROM EMBRIAOCLASSIFICACAO ec ORDER BY ec.CDEMBRIAOCLASSIFICACAO;

SELECT '@RESULTADOGINE@' || CAST(rg.CDRESULTADOEXAMEGINECOLOGICO AS VARCHAR(10))
  || '~|~' || COALESCE(rg.NOMERESUMIDO, '')
  || '~|~' || COALESCE(rg.NOMECOMPLETO, '')
  || '~|~' || COALESCE(rg.TIPO, '')
  || '~|~' || COALESCE(CAST(rg.PADRAO AS VARCHAR(2)), '') AS "LINHA"
FROM RESULTADOEXAMEGINECOLOGICO rg
ORDER BY rg.CDRESULTADOEXAMEGINECOLOGICO;
