import { useEffect, useState } from "react";
import { Button, ErrorBox, hoje, dataBR } from "../financeiro/financeiro-ui";
import { classeInput } from "../financeiro/PainelCadastro";
import { listarPartidasNutricionais, type PartidaNutricional } from "../pecuaria/rebanho/nutricao/api";
export type DistribuicaoPartida = { partidaId?: string; codigo?: string; validade?: string | null; quantidade: string };
export function SelecaoPartidas({ produtoId, propriedadeId, dataFato, quantidade, unidade, saida, valor, onChange }: { produtoId: string; propriedadeId?: number; dataFato?: string; quantidade?: string; unidade?: string; saida: boolean; valor: DistribuicaoPartida[]; onChange: (p: DistribuicaoPartida[]) => void }) {
  const [partidas, setPartidas] = useState<PartidaNutricional[]>([]);
  const [erro, setErro] = useState<string | null>(null);
  const [carregando, setCarregando] = useState(false);
  useEffect(() => { let vivo = true; setPartidas([]); setCarregando(true); listarPartidasNutricionais(produtoId, propriedadeId).then((p) => { if (vivo) { setPartidas(p); setErro(null); } }).catch((e: unknown) => { if (vivo) setErro(e instanceof Error ? e.message : String(e)); }).finally(() => { if (vivo) setCarregando(false); }); return () => { vivo = false; }; }, [produtoId, propriedadeId]);
  useEffect(() => {
    if (!valor.length) onChange([{ quantidade: quantidade ?? "" }]);
    else if (valor.length === 1 && quantidade != null && valor[0].quantidade !== quantidade) onChange([{ ...valor[0], quantidade }]);
  }, [valor, quantidade, onChange]);
  const sugerida = partidas.filter((p) => Number(p.saldo) > 0 && p.validade && p.validade.slice(0, 10) >= (dataFato || hoje())).sort((a, b) => (a.validade ?? "").localeCompare(b.validade ?? ""))[0];
  function alterar(i: number, patch: Partial<DistribuicaoPartida>) { onChange(valor.map((v, j) => i === j ? { ...v, ...patch } : v)); }
  function selecionar(i: number, id: string) {
    const p = partidas.find((l) => l.id === id);
    alterar(i, { partidaId: id || undefined, codigo: p?.codigo, validade: p?.validade?.slice(0, 10) ?? null });
  }
  return <fieldset className="mt-3 grid gap-3 rounded-lg border border-border p-3"><legend className="px-1 text-sm font-semibold">Lote do produto</legend><ErrorBox erro={erro} />{carregando && <p className="text-sm">Carregando lotes…</p>}<p className="text-xs text-ink-3">Identifique o lote da quantidade aplicada ou movimentada. Para usar mais de um, divida a quantidade entre os lotes.</p>{saida && sugerida && <p className="text-xs">Vencimento conhecido mais próximo: <strong>{sugerida.codigo}</strong> · {dataBR(sugerida.validade!)}. Confirme a escolha abaixo.</p>}{valor.map((v, i) => <div key={i} className="grid gap-2 rounded-lg border border-border p-2"><label className="text-sm">{saida ? "Lote" : "Lote existente (opcional)"}<select aria-label={`Lote ${i + 1}`} required={saida} className={classeInput} value={v.partidaId ?? ""} onChange={(e) => selecionar(i, e.target.value)}><option value="">{saida ? "Selecione um lote" : "Cadastrar novo lote"}</option>{partidas.map((p) => <option key={p.id} value={p.id}>{p.origemRastreio === "LEGADO_NAO_IDENTIFICADO" ? "Estoque sem lote identificado" : p.codigo} · saldo {Number(p.saldo).toLocaleString("pt-BR")} {unidade ?? ""} · validade {p.validade ? dataBR(p.validade) : "não informada"}</option>)}</select></label>{!saida && !v.partidaId && <div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">Código do lote<input aria-label={`Código do lote ${i + 1}`} required placeholder="Código do fabricante" value={v.codigo ?? ""} onChange={(e) => alterar(i, { codigo: e.target.value })} className={classeInput} /></label><label className="text-sm">Validade (opcional)<input aria-label={`Validade do lote ${i + 1}`} type="date" value={v.validade ?? ""} onChange={(e) => alterar(i, { validade: e.target.value || null })} className={classeInput} /></label></div>}<label className="text-sm">Quantidade {unidade && `(${unidade})`}<input aria-label={`Quantidade do lote ${i + 1}`} required type="number" min="0.001" step="0.001" readOnly={valor.length === 1 && quantidade != null} value={v.quantidade} onChange={(e) => alterar(i, { quantidade: e.target.value })} className={classeInput} /></label>{valor.length > 1 && <Button secondary onClick={() => onChange(valor.filter((_, j) => i !== j))}>Remover lote</Button>}</div>)}<Button secondary onClick={() => onChange([...valor, { quantidade: "" }])}>{valor.length <= 1 ? "Dividir entre lotes" : "Adicionar outro lote"}</Button>{valor.length > 1 && <p className="text-xs text-ink-3">A soma deve conferir com {quantidade ?? "a quantidade do movimento"} {unidade ?? ""}.</p>}</fieldset>;
}
