import { useEffect, useState } from "react";
import { Button, ErrorBox, hoje } from "../financeiro/financeiro-ui";
import { classeInput } from "../financeiro/PainelCadastro";
import { listarPartidasNutricionais, type PartidaNutricional } from "../pecuaria/rebanho/nutricao/api";
export type DistribuicaoPartida = { partidaId?: string; codigo?: string; validade?: string | null; quantidade: string };
export function SelecaoPartidas({ produtoId, propriedadeId, dataFato, saida, valor, onChange }: { produtoId: string; propriedadeId?: number; dataFato?: string; saida: boolean; valor: DistribuicaoPartida[]; onChange: (p: DistribuicaoPartida[]) => void }) {
  const [partidas, setPartidas] = useState<PartidaNutricional[]>([]);
  const [erro, setErro] = useState<string | null>(null);
  useEffect(() => { let vivo = true; setPartidas([]); listarPartidasNutricionais(produtoId, propriedadeId).then((p) => { if (vivo) { setPartidas(p); setErro(null); } }).catch((e: unknown) => { if (vivo) setErro(e instanceof Error ? e.message : String(e)); }); return () => { vivo = false; }; }, [produtoId, propriedadeId]);
  const sugerida = partidas.filter((p) => Number(p.saldo) > 0 && p.validade && p.validade.slice(0, 10) >= (dataFato || hoje())).sort((a, b) => (a.validade ?? "").localeCompare(b.validade ?? ""))[0];
  function alterar(i: number, patch: Partial<DistribuicaoPartida>) { onChange(valor.map((v, j) => i === j ? { ...v, ...patch } : v)); }
  return <fieldset className="mt-3 grid gap-2 rounded-lg border border-border p-3"><legend className="px-1 text-sm font-semibold">Distribuição por partida</legend><ErrorBox erro={erro} /><p className="text-xs text-ink-3">A soma deve ser igual à quantidade do item, na mesma unidade. Confira validade e saldo. Validade desconhecida não será escolhida automaticamente.</p>{saida && sugerida && <p className="text-xs">Vencimento conhecido mais próximo: {sugerida.codigo} · {sugerida.validade?.slice(0, 10)}. Sugestão apenas; confirme a seleção.</p>}{valor.map((v, i) => <div key={i} className="grid gap-2 sm:grid-cols-3">{saida ? <select aria-label={`Partida ${i + 1}`} required className={classeInput} value={v.partidaId ?? ""} onChange={(e) => alterar(i, { partidaId: e.target.value })}><option value="">Selecione</option>{partidas.map((p) => <option key={p.id} value={p.id}>{p.codigo} · saldo {p.saldo} · vence {p.validade?.slice(0, 10) ?? "desconhecido"}</option>)}</select> : <><input aria-label={`Código da partida ${i + 1}`} required placeholder="Código do fabricante" value={v.codigo ?? ""} onChange={(e) => alterar(i, { codigo: e.target.value })} className={classeInput} /><input aria-label={`Validade da partida ${i + 1}`} type="date" value={v.validade ?? ""} onChange={(e) => alterar(i, { validade: e.target.value || null })} className={classeInput} /></>}<input aria-label={`Quantidade da partida ${i + 1}`} required type="number" min="0.001" step="0.001" value={v.quantidade} onChange={(e) => alterar(i, { quantidade: e.target.value })} className={classeInput} /><Button secondary onClick={() => onChange(valor.filter((_, j) => i !== j))}>Remover partida</Button></div>)}<Button secondary onClick={() => onChange([...valor, { quantidade: "" }])}>Adicionar partida</Button></fieldset>;
}
