import crypto from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { prisma } from "../../../db.js";
import { cadastrar, mudarDestino } from "../rebanho/animais.js";
import { cadastrarAnimalSchema } from "../rebanho/schemas.js";
import { hojeFazenda } from "../rebanho/regras.js";
import { anularAplicacao, carenciaAnimal, criarAplicacao, criarAplicacoesColetivas, listarAplicacoes, reconciliarOrigem } from "./aplicacoes.js";
import { obterAplicacao } from "./detalhes.js";
import { salvarTipoAplicacao } from "./tiposAplicacao.js";
import { listarPartidas } from "../../estoque/partidas.js";

const comBanco = process.env.PECUARIA_DB_INTEGRATION === "1" ? describe : describe.skip;
const run = crypto.randomUUID().slice(0, 8);
const ids = { sitio: 0, animal: "", produto: "", tipo: "", partida: "" };
const hoje = hojeFazenda();
const antes = (n: number) => new Date(Date.parse(hoje) - n * 86400000).toISOString().slice(0, 10);
afterAll(async () => {
  if (!ids.sitio) return;
  const movimentos = await prisma.movimentoEstoque.findMany({ where: { produtoId: ids.produto }, select: { id: true } });
  await prisma.auditoriaPecuaria.deleteMany({ where: { OR: [{ animalId: ids.animal }, { entidadeId: ids.tipo }] } });
  await prisma.aplicacaoProduto.deleteMany({ where: { animalId: ids.animal } });
  await prisma.requisicaoPecuaria.deleteMany({ where: { propriedadeId: ids.sitio } });
  await prisma.auditoriaFinanceira.deleteMany({ where: { entidadeId: { in: movimentos.map((m) => m.id) } } });
  // Desmonta somente a fixture descartável; a UI não permite desligar rastreio.
  await prisma.produto.update({ where: { id: ids.produto }, data: { rastrearPartidas: false } });
  await prisma.alocacaoPartidaEstoque.deleteMany({ where: { partida: { produtoId: ids.produto } } });
  await prisma.movimentoEstoque.deleteMany({ where: { produtoId: ids.produto } });
  await prisma.partidaProduto.deleteMany({ where: { produtoId: ids.produto, lotePrincipalId: { not: null } } });
  await prisma.partidaProduto.deleteMany({ where: { produtoId: ids.produto } });
  await prisma.produto.deleteMany({ where: { id: ids.produto } });
  await prisma.destinoAnimal.deleteMany({ where: { animalId: ids.animal } });
  await prisma.localizacaoAnimal.deleteMany({ where: { animalId: ids.animal } });
  await prisma.animal.deleteMany({ where: { id: ids.animal } });
  await prisma.tipoAplicacaoSanitaria.deleteMany({ where: { id: ids.tipo } });
  await prisma.propriedade.deleteMany({ where: { id: ids.sitio } });
});
comBanco("contratos da interface sanitária V3", () => {
  it("baixa 10 de 50 mL sem Serviço, conserva nome do tipo e revisa leite após mudança de finalidade", async () => {
    const sitio = await prisma.propriedade.create({ data: { nome: `UI V3 ${run}` } }); ids.sitio = sitio.id;
    const animal = await cadastrar(cadastrarAnimalSchema.parse({ brinco: `UI${run}`, sexo: "F", origem: "COMPRADO", aptidao: "CORTE", propriedadeId: sitio.id, dataNascimento: antes(100), dataEntrada: antes(20) }), null); ids.animal = animal.id;
    const tipo = await salvarTipoAplicacao({ nome: `Personalizado ${run}` }, null); ids.tipo = tipo.id;
    const produto = await prisma.produto.create({ data: { nome: `Medicamento ${run}`, unidade: "ML", usoSanitario: true, rastrearPartidas: true } }); ids.produto = produto.id;
    const partida = await prisma.partidaProduto.create({ data: { produtoId: produto.id, codigo: `FAB-${run}`, validade: new Date(Date.parse(hoje) + 365 * 86400000) } }); ids.partida = partida.id;
    await prisma.movimentoEstoque.create({ data: { produtoId: produto.id, propriedadeId: sitio.id, tipo: "ENTRADA", origem: "INVENTARIO_INICIAL", data: new Date(antes(10)), quantidade: 50, custoUnitario: 2, valorTotal: 100, alocacaoPartidaEstoques: { create: { partidaId: partida.id, quantidade: 50 } } } });
    const input = { animalId: animal.id, propriedadeId: sitio.id, data: antes(1), aplicadaEm: `${antes(1)}T10:00:00-03:00`, tipoAplicacaoId: tipo.id, origemInsumo: "BAIXA_ESTOQUE" as const, produtoId: produto.id, partidaId: partida.id, nomeProdutoAplicado: produto.nome, dose: "10", unidadeDose: "ML" as const, responsavel: "Funcionário da fazenda", estadoCarenciaLeite: "NAO_APLICAVEL" as const, estadoCarenciaCarne: "INFORMADO" as const, carenciaLeiteHoras: null, carenciaCarneHoras: 0 };
    const aplicacao = await criarAplicacao(input, null);
    expect(aplicacao.operacaoServicoId).toBeNull();
    expect(aplicacao.responsavel).toBe("Funcionário da fazenda");
    const saida = await prisma.movimentoEstoque.findUniqueOrThrow({ where: { id: aplicacao.movimentoEstoqueId! } });
    expect(saida.quantidade.toString()).toBe("10");
    expect(50 - saida.quantidade.toNumber()).toBe(40);
    expect((await listarPartidas(produto.id, sitio.id)).find((p) => p.id === partida.id)?.saldo).toBe("40");
    expect(aplicacao.partidaCodigoSnapshot).toBe(partida.codigo);
    expect((await carenciaAnimal(animal.id, sitio.id)).leite).toEqual({ estado: "NAO_APLICAVEL" });
    await salvarTipoAplicacao({ nome: `Renomeado ${run}`, ativo: false }, null, tipo.id);
    expect((await prisma.aplicacaoProduto.findUniqueOrThrow({ where: { id: aplicacao.id } })).tipoAplicacaoNomeSnapshot).toBe(tipo.nome);
    await expect(criarAplicacao(input, null)).rejects.toThrow(/ativo/);
    await mudarDestino({ animalId: animal.id, data: hoje, aptidao: "LEITE", papelReprodutivo: "NENHUM" }, null, sitio.id);
    expect(await carenciaAnimal(animal.id, sitio.id)).toMatchObject({ leite: { estado: "NAO_INFORMADO" }, revisaoLeitePendente: true });
    await anularAplicacao(aplicacao.id, sitio.id, "Correção comprovada da aplicação", null);
    expect((await listarPartidas(produto.id, sitio.id)).find((p) => p.id === partida.id)?.saldo).toBe("50");
    expect((await carenciaAnimal(animal.id, sitio.id)).leite).toEqual({ estado: "NENHUMA" });
  });
  it("reconcilia estoque sem mudar o fato e preserva a justificativa original", async () => {
    await salvarTipoAplicacao({ ativo: true }, null, ids.tipo);
    const produto = await prisma.produto.findUniqueOrThrow({ where: { id: ids.produto } });
    const input = { animalId: ids.animal, propriedadeId: ids.sitio, data: hoje, aplicadaEm: `${hoje}T10:00:00-03:00`, tipoAplicacaoId: ids.tipo, origemInsumo: "SEM_ORIGEM_JUSTIFICADA" as const, nomeProdutoAplicado: produto.nome, dose: "10", unidadeDose: "ML" as const, justificativaSemOrigem: "Aplicado em campo; origem ainda não localizada", carenciaLeiteHoras: 0, carenciaCarneHoras: 0 };
    const aplicada = await criarAplicacao(input, null);
    const reconciliada = await reconciliarOrigem(aplicada.id, ids.sitio, { origemInsumo: "BAIXA_ESTOQUE", produtoId: ids.produto, partidaId: ids.partida, motivo: "Conferência do medicamento no almoxarifado" }, null);
    expect(reconciliada.justificativaSemOrigem).toBe(input.justificativaSemOrigem);
    expect(reconciliada.nomeProdutoAplicado).toBe(aplicada.nomeProdutoAplicado);
    expect(reconciliada.dose?.toString()).toBe(aplicada.dose?.toString());
    expect(reconciliada.movimentoEstoqueId).not.toBeNull();
    await expect(reconciliarOrigem(aplicada.id, ids.sitio, { origemInsumo: "BAIXA_ESTOQUE", produtoId: ids.produto, motivo: "Reenvio indevido" }, null)).rejects.toThrow(/pendente/);
    const auditoria = await prisma.auditoriaPecuaria.findFirst({ where: { entidadeId: aplicada.id, acao: "ORIGEM_RECONCILIADA" } });
    expect(auditoria).not.toBeNull();
  });
  it("confirma coletivo uma única vez e desfaz integralmente o conjunto inválido", async () => {
    const item = { animalId: ids.animal, propriedadeId: ids.sitio, data: hoje, aplicadaEm: `${hoje}T11:00:00-03:00`, tipoAplicacaoId: ids.tipo, origemInsumo: "BAIXA_ESTOQUE" as const, produtoId: ids.produto, partidaId: ids.partida, nomeProdutoAplicado: "Medicamento", dose: "1", unidadeDose: "ML" as const, carenciaLeiteHoras: 0, carenciaCarneHoras: 0 };
    const input = { chave: crypto.randomUUID(), propriedadeId: ids.sitio, itens: [item] };
    const resultado = await criarAplicacoesColetivas(input, null);
    expect(await criarAplicacoesColetivas(input, null)).toEqual(resultado);
    await expect(criarAplicacoesColetivas({ ...input, itens: [{ ...item, dose: "2" }] }, null)).rejects.toThrow(/Chave/);
    const antes = await prisma.aplicacaoProduto.count({ where: { animalId: ids.animal } });
    await expect(criarAplicacoesColetivas({ chave: crypto.randomUUID(), propriedadeId: ids.sitio, itens: [item, { ...item, animalId: crypto.randomUUID() }] }, null)).rejects.toThrow(/Linha 2/);
    expect(await prisma.aplicacaoProduto.count({ where: { animalId: ids.animal } })).toBe(antes);
  });
  it("aplicação em alias desconhecido exige ciência e consome saldo da raiz", async () => {
    const raiz = await prisma.partidaProduto.create({ data: { produtoId: ids.produto, codigo: `SEM-VALIDADE-${run}`, validade: null } });
    const alias = await prisma.partidaProduto.create({ data: { produtoId: ids.produto, codigo: `SEM-VALIDADE-ALIAS-${run}`, validade: null, lotePrincipalId: raiz.id } });
    await prisma.movimentoEstoque.create({ data: { produtoId: ids.produto, propriedadeId: ids.sitio, tipo: "ENTRADA", origem: "INVENTARIO_INICIAL", data: new Date(antes(1)), quantidade: 50, custoUnitario: 2, valorTotal: 100, alocacaoPartidaEstoques: { create: { partidaId: alias.id, quantidade: 50 } } } });
    const input = { animalId: ids.animal, propriedadeId: ids.sitio, data: hoje, aplicadaEm: `${hoje}T11:00:00-03:00`, tipoAplicacaoId: ids.tipo, origemInsumo: "BAIXA_ESTOQUE" as const, produtoId: ids.produto, partidaId: alias.id, nomeProdutoAplicado: "Medicamento", dose: "10", unidadeDose: "ML" as const, carenciaLeiteHoras: 0, carenciaCarneHoras: 0 };
    await expect(criarAplicacao(input, null)).rejects.toThrow(/ciência/);
    const aplicada = await criarAplicacao({ ...input, cienciaValidadeDesconhecida: true }, null);
    const nomeProduto = (await prisma.produto.findUniqueOrThrow({ where: { id: ids.produto } })).nome;
    expect((await listarAplicacoes(ids.animal, ids.sitio)).find((a) => a.id === aplicada.id)?.loteNome).toBe(`${nomeProduto} — validade não informada`);
    expect(await obterAplicacao(aplicada.id, ids.sitio)).toMatchObject({ loteNome: `${nomeProduto} — validade não informada`, lotePrincipalId: raiz.id, partidaCodigoSnapshot: raiz.codigo });
    expect((await prisma.alocacaoPartidaEstoque.findFirstOrThrow({ where: { movimentoEstoqueId: aplicada.movimentoEstoqueId! } })).partidaId).toBe(raiz.id);
    expect((await listarPartidas(ids.produto, ids.sitio)).find((p) => p.id === raiz.id)?.saldo).toBe("40");
    expect((await prisma.auditoriaPecuaria.findFirstOrThrow({ where: { entidadeId: aplicada.id, acao: "REGISTRO" } })).depois).toMatchObject({ cienciaValidadeDesconhecida: true });
    await anularAplicacao(aplicada.id, ids.sitio, "Correção da aplicação sem validade", null);
    expect((await listarPartidas(ids.produto, ids.sitio)).find((p) => p.id === raiz.id)?.saldo).toBe("50");
  });
});
