import crypto from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { prisma } from "../../../db.js";
import { cadastrar, darBaixa, desfazerLocalizacao, editar, movimentar } from "../rebanho/animais.js";
import { cadastrarAnimalSchema } from "../rebanho/schemas.js";
import { hojeFazenda } from "../rebanho/regras.js";
import { corrigirExame, criarTipoExame, listarExames, registrarExame, registrarExameColetivo } from "./exames.js";
import { criarProtocolo, iniciarExecucao, iniciarExecucaoColetivo, listarTarefas, publicarProtocolo } from "./protocolos.js";
import { salvarRateio } from "./rateios.js";

const describeComBanco = process.env.PECUARIA_DB_INTEGRATION === "1" ? describe : describe.skip;
const run = crypto.randomUUID().slice(0, 8);
const propriedadeIds: number[] = [];
const animalIds: string[] = [];
const protocoloIds: string[] = [];
const tipoIds: string[] = [];
const execucaoIds: string[] = [];
const servicoIds: string[] = [];

afterAll(async () => {
  if (!propriedadeIds.length) return;
  await prisma.requisicaoPecuaria.deleteMany({ where: { propriedadeId: { in: propriedadeIds } } });
  await prisma.auditoriaPecuaria.deleteMany({ where: { OR: [
    { animalId: { in: animalIds } }, { entidadeId: { in: [...protocoloIds, ...tipoIds, ...execucaoIds] } },
  ] } });
  await prisma.exameAnimal.deleteMany({ where: { animalId: { in: animalIds } } });
  await prisma.baixaAnimal.deleteMany({ where: { animalId: { in: animalIds } } });
  await prisma.tarefaSanitaria.deleteMany({ where: { execucaoId: { in: execucaoIds } } });
  await prisma.execucaoProtocoloSanitario.deleteMany({ where: { id: { in: execucaoIds } } });
  await prisma.etapaProtocoloSanitario.deleteMany({ where: { protocoloId: { in: protocoloIds } } });
  await prisma.protocoloSanitario.deleteMany({ where: { id: { in: protocoloIds } } });
  await prisma.tipoExame.deleteMany({ where: { id: { in: tipoIds } } });
  await prisma.destinoAnimal.deleteMany({ where: { animalId: { in: animalIds } } });
  await prisma.localizacaoAnimal.deleteMany({ where: { animalId: { in: animalIds } } });
  await prisma.movimentacaoAnimal.deleteMany({ where: { animalId: { in: animalIds } } });
  await prisma.movimentacao.deleteMany({ where: { propriedadeDestinoId: { in: propriedadeIds } } });
  await prisma.animal.deleteMany({ where: { id: { in: animalIds } } });
  await prisma.operacao.deleteMany({ where: { id: { in: servicoIds } } });
  await prisma.propriedade.deleteMany({ where: { id: { in: propriedadeIds } } });
});

describeComBanco("protocolo e exame com PostgreSQL", () => {
  it("agendar uma etapa não consome estoque; o exame realizado resolve a tarefa", async () => {
    const propriedade = await prisma.propriedade.create({ data: { nome: `Pec V3 protocolo ${run}` } });
    propriedadeIds.push(propriedade.id);
    const animal = await cadastrar(cadastrarAnimalSchema.parse({ brinco: `PR${run}`, sexo: "F", origem: "COMPRADO", aptidao: "LEITE",
      dataNascimento: "2024-01-01", dataEntrada: "2026-08-01", propriedadeId: propriedade.id }), null);
    animalIds.push(animal.id);
    const tipo = await criarTipoExame({ nome: `Exame V3 ${run}`, tipoResultado: "OPCAO", opcoes: ["NEGATIVO", "POSITIVO"] }, null);
    tipoIds.push(tipo.id);
    const protocolo = await criarProtocolo({ nome: `Protocolo V3 ${run}`, etapas: [{ tipo: "EXAME", diaRelativo: 0, tipoExameId: tipo.id }] }, null);
    protocoloIds.push(protocolo.id);
    await publicarProtocolo(protocolo.id, null);
    const antes = await prisma.movimentoEstoque.count();
    const data = hojeFazenda();
    const servico = await prisma.operacao.create({ data: { tipo: "SERVICO", status: "CONFIRMADA", data: new Date(data), valorTotal: 1000, propriedadeId: propriedade.id } });
    servicoIds.push(servico.id);
    const execucao = await iniciarExecucao({ protocoloId: protocolo.id, animalId: animal.id, propriedadeId: propriedade.id, inicio: data, operacaoServicoId: servico.id }, null);
    execucaoIds.push(execucao.id);
    expect(execucao.tarefas).toHaveLength(1);
    expect((await listarTarefas(propriedade.id, animal.id))[0].situacao).toBe("PENDENTE");
    expect(await prisma.movimentoEstoque.count()).toBe(antes);
    const exame = await registrarExame({ animalId: animal.id, propriedadeId: propriedade.id, tipoExameId: tipo.id, data,
      resultadoOpcao: "NEGATIVO", tarefaId: execucao.tarefas[0].id }, null);
    await salvarRateio({ servicoId: servico.id, propriedadeId: propriedade.id, tipo: "PROTOCOLO", id: execucao.id, valor: "100", motivo: "Rateio do atendimento completo" }, null);
    await expect(salvarRateio({ servicoId: servico.id, propriedadeId: propriedade.id, tipo: "EXAME", id: exame.id, valor: "10", motivo: "Tentativa de duplicar protocolo e exame" }, null)).rejects.toThrow(/protocolo e/);
    await salvarRateio({ servicoId: servico.id, propriedadeId: propriedade.id, tipo: "PROTOCOLO", id: execucao.id, valor: null, motivo: "Retirar antes de atribuir aos fatos" }, null);
    await salvarRateio({ servicoId: servico.id, propriedadeId: propriedade.id, tipo: "EXAME", id: exame.id, valor: "100", motivo: "Atribuição ao exame confirmado" }, null);
    expect((await listarTarefas(propriedade.id, animal.id))[0].situacao).toBe("REALIZADA");
    expect(await prisma.movimentoEstoque.count()).toBe(antes);
  });
  it("coletivos de protocolos e exames são atômicos e o reenvio não duplica fatos", async () => {
    const propriedadeId = propriedadeIds[0];
    const animalId = animalIds[0];
    const data = hojeFazenda();
    const segundo = await cadastrar(cadastrarAnimalSchema.parse({ brinco: `PC${run}`, sexo: "M", origem: "COMPRADO", aptidao: "CORTE", dataNascimento: "2024-01-01", dataEntrada: "2026-08-01", propriedadeId }), null);
    animalIds.push(segundo.id);
    const protocolo = { protocoloId: protocoloIds[0], animalId, propriedadeId, inicio: data };
    const exame = { animalId, propriedadeId, tipoExameId: tipoIds[0], data };
    const chaveProtocolo = crypto.randomUUID();
    const chaveExame = crypto.randomUUID();
    const antesP = await prisma.execucaoProtocoloSanitario.count({ where: { animalId } });
    const antesE = await prisma.exameAnimal.count({ where: { animalId } });
    const invalidosP = { chave: crypto.randomUUID(), propriedadeId, itens: [protocolo, { ...protocolo, animalId: segundo.id, protocoloId: crypto.randomUUID() }] };
    const invalidosE = { chave: crypto.randomUUID(), propriedadeId, itens: [exame, { ...exame, animalId: segundo.id, tipoExameId: crypto.randomUUID() }] };
    await expect(iniciarExecucaoColetivo(invalidosP, null)).rejects.toThrow();
    await expect(registrarExameColetivo(invalidosE, null)).rejects.toThrow();
    expect(await prisma.execucaoProtocoloSanitario.count({ where: { animalId } })).toBe(antesP);
    expect(await prisma.exameAnimal.count({ where: { animalId } })).toBe(antesE);
    const p = { chave: chaveProtocolo, propriedadeId, itens: [protocolo] };
    const e = { chave: chaveExame, propriedadeId, itens: [exame] };
    expect(await iniciarExecucaoColetivo(p, null)).toEqual(await iniciarExecucaoColetivo(p, null));
    expect(await registrarExameColetivo(e, null)).toEqual(await registrarExameColetivo(e, null));
    expect(await prisma.execucaoProtocoloSanitario.count({ where: { animalId } })).toBe(antesP + 1);
    expect(await prisma.exameAnimal.count({ where: { animalId } })).toBe(antesE + 1);
    const execucoes = await prisma.execucaoProtocoloSanitario.findMany({ where: { animalId }, select: { id: true } });
    execucaoIds.push(...execucoes.map((v) => v.id).filter((id) => !execucaoIds.includes(id)));
  });
  it("anulação preserva tentativa; agenda acompanha transferência e fatos mantêm sítio original", async () => {
    const origem = propriedadeIds[0];
    const destino = await prisma.propriedade.create({ data: { nome: `Destino agenda ${run}` } });
    propriedadeIds.push(destino.id);
    const animal = await cadastrar(cadastrarAnimalSchema.parse({ brinco: `TR${run}`, sexo: "F", origem: "COMPRADO", aptidao: "LEITE", dataNascimento: "2024-01-01", dataEntrada: "2026-08-01", propriedadeId: origem }), null);
    animalIds.push(animal.id);
    const execucao = await iniciarExecucao({ animalId: animal.id, propriedadeId: origem, protocoloId: protocoloIds[0], inicio: "2026-09-01" }, null);
    execucaoIds.push(execucao.id);
    const tarefaId = execucao.tarefas[0].id;
    const primeiro = await registrarExame({ animalId: animal.id, propriedadeId: origem, data: "2026-09-01", tipoExameId: tipoIds[0], tarefaId }, null);
    await expect(registrarExame({ animalId: animal.id, propriedadeId: origem, data: "2026-09-02", tipoExameId: tipoIds[0], tarefaId }, null)).rejects.toThrow(/já realizada/);
    await corrigirExame(primeiro.id, origem, { motivo: "Coleta descartada antes da análise", anular: true }, null);
    expect((await listarTarefas(origem, animal.id))[0].situacao).toBe("PENDENTE");
    await movimentar({ animalIds: [animal.id], propriedadeId: destino.id, data: "2026-09-10" }, null);
    expect(await listarTarefas(origem, animal.id)).toEqual([]);
    expect((await listarTarefas(destino.id, animal.id))[0]).toMatchObject({ propriedadeAtualId: destino.id, execucao: { propriedadeId: origem } });
    const entrada = { chave: crypto.randomUUID(), animalId: animal.id, propriedadeId: destino.id, data: "2026-09-10", tipoExameId: tipoIds[0], tarefaId };
    const segundo = await registrarExame(entrada, null);
    expect((await registrarExame(entrada, null)).id).toBe(segundo.id);
    expect(segundo.id).not.toBe(primeiro.id);
    const tarefa = (await listarTarefas(destino.id, animal.id))[0];
    expect(tarefa.aplicacao).toBeNull();
    expect(tarefa.exame?.id).toBe(segundo.id);
    expect(tarefa.exames).toHaveLength(2);
    expect(await listarExames(animal.id, origem)).toEqual([expect.objectContaining({ id: primeiro.id, status: "ANULADO", tarefaId })]);
    await expect(desfazerLocalizacao(animal.id, null)).rejects.toThrow(/sítio de fatos/);
    await expect(darBaixa({ animalId: animal.id, tipo: "MORTE", data: "2026-09-09" }, null)).rejects.toThrow(/antecede fatos/);
    await expect(editar(animal.id, { dataEntrada: "2026-09-11" }, null)).rejects.toThrow();
    await darBaixa({ animalId: animal.id, tipo: "MORTE", data: "2026-09-20" }, null);
    const retroativo = await registrarExame({ animalId: animal.id, propriedadeId: origem, data: "2026-09-05", tipoExameId: tipoIds[0] }, null);
    expect(retroativo.propriedadeId).toBe(origem);
    await registrarExame({ animalId: animal.id, propriedadeId: destino.id, data: "2026-09-20", tipoExameId: tipoIds[0] }, null);
    await expect(registrarExame({ animalId: animal.id, propriedadeId: destino.id, data: "2026-09-21", tipoExameId: tipoIds[0] }, null)).rejects.toThrow(/após a baixa/);
    await expect(registrarExame({ animalId: animal.id, propriedadeId: origem, data: "2026-09-10", tipoExameId: tipoIds[0] }, null)).rejects.toThrow(/não estava/);
  });
});
